import { COMMON_STRINGS } from "./common";
import { AUTH_STRINGS } from "./auth";
import { ROLE_STRINGS } from "./roles";
import { DASHBOARD_STRINGS } from "./dashboard";

export const STRINGS = {
  APP_NAME: COMMON_STRINGS.APP_NAME,
  APP_DESCRIPTION: COMMON_STRINGS.APP_DESCRIPTION,
  AUTH: AUTH_STRINGS,
  ROLES: ROLE_STRINGS,
  COMMON: COMMON_STRINGS,
  DASHBOARD: DASHBOARD_STRINGS,
} as const;

export { COMMON_STRINGS, AUTH_STRINGS, ROLE_STRINGS, DASHBOARD_STRINGS };
