import { COLORS } from "@/constants/colors";

export const styles = {
  container: {
    maxWidth: "900px",
    margin: "0 auto",
  },
  headerSubtitle: {
    color: COLORS.text.muted,
    marginBottom: "20px",
  },
  tabsRow: {
    display: "flex",
    gap: "10px",
    marginBottom: "20px",
    borderBottom: "1px solid #e5e7eb",
    paddingBottom: "10px",
  },
  tabButton: (isActive: boolean) => ({
    padding: "8px 16px",
    backgroundColor: isActive ? COLORS.status.info : "transparent",
    color: isActive ? "white" : COLORS.text.secondary,
    border: isActive ? "none" : "1px solid #d1d5db",
    borderRadius: "4px",
    fontWeight: "bold" as const,
    cursor: "pointer",
  }),
  layoutContainer: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "20px",
  },
  promptTip: {
    backgroundColor: "#eff6ff",
    borderLeft: `4px solid ${COLORS.status.info}`,
    padding: "12px",
    margin: "15px 0",
    borderRadius: "4px",
    fontSize: "13px",
    color: "#1e3a8a",
  },
  promptList: {
    margin: "5px 0 0 15px",
    padding: 0,
  },
  formContainer: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "15px",
  },
  formContainerWithMargin: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "15px",
    marginTop: "15px",
  },
  fieldLabel: {
    display: "block",
    fontWeight: "bold" as const,
    marginBottom: "5px",
  },
  selectInput: {
    width: "100%",
    padding: "8px",
    borderRadius: "4px",
    border: "1px solid #ccc",
  },
  textareaInput: {
    width: "100%",
    padding: "8px",
    borderRadius: "4px",
    border: "1px solid #ccc",
    fontFamily: "inherit",
  },
  errorBanner: {
    color: COLORS.status.error,
    backgroundColor: "#fee2e2",
    padding: "10px",
    borderRadius: "4px",
  },
  submitButton: (loading: boolean) => ({
    padding: "10px 20px",
    backgroundColor: COLORS.status.info,
    color: "white",
    border: "none",
    borderRadius: "4px",
    fontWeight: "bold" as const,
    cursor: loading ? "not-allowed" : "pointer",
    alignSelf: "flex-start" as const,
  }),
  resultsTitleRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  modelBadge: {
    fontSize: "13px",
    color: "#1e40af",
    backgroundColor: "#eff6ff",
    padding: "4px 8px",
    borderRadius: "4px",
    fontWeight: "bold" as const,
  },
  loadingText: {
    color: COLORS.text.muted,
    fontStyle: "italic",
    padding: "15px 0",
  },
  resultsContainer: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "15px",
    marginTop: "15px",
  },
  matchAnalysisBanner: {
    padding: "15px",
    backgroundColor: "#f9fafb",
    borderLeft: `4px solid ${COLORS.status.success}`,
    borderRadius: "4px",
    fontSize: "14px",
    lineHeight: "1.6",
    color: "#1f2937",
  },
  analysisTitleText: {
    margin: "5px 0 0 0",
  },
  gapAnalysisBanner: {
    padding: "15px",
    border: "1px solid #fee2e2",
    borderRadius: "6px",
    backgroundColor: "#fef2f2",
    borderLeft: `5px solid ${COLORS.status.error}`,
  },
  gapText: {
    margin: 0,
    fontSize: "14px",
    color: "#b91c1c",
    lineHeight: "1.4",
  },
  candidateCard: {
    padding: "15px",
    border: "1px solid #e5e7eb",
    borderRadius: "6px",
    backgroundColor: "#f9fafb",
  },
  candidateHeaderRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "8px",
  },
  candidateName: {
    margin: 0,
    color: "#1f2937",
  },
  suggestedAllocationBadge: {
    backgroundColor: "#dbeafe",
    color: "#1e40af",
    padding: "2px 8px",
    borderRadius: "12px",
    fontSize: "12px",
    fontWeight: "bold" as const,
  },
  reasonText: {
    margin: "0 0 10px 0",
    fontSize: "14px",
    color: "#4b5563",
    lineHeight: "1.5",
  },
  candidateMetaGrid: {
    marginTop: "10px",
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "10px",
    fontSize: "13px",
    borderTop: "1px solid #e5e7eb",
    paddingTop: "10px",
    color: "#374151",
    marginBottom: "10px",
  },
  spanTwoCols: {
    gridColumn: "span 2",
  },
  allocateButton: {
    padding: "6px 12px",
    backgroundColor: COLORS.status.success,
    color: "white",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "bold" as const,
  },
  notesDisclaimer: {
    fontSize: "12px",
    color: COLORS.text.muted,
    borderTop: "1px solid #e5e7eb",
    paddingTop: "10px",
    margin: "10px 0 0 0",
  },
  teamRoleCard: (filled: boolean) => ({
    padding: "15px",
    border: "1px solid #e5e7eb",
    borderRadius: "6px",
    backgroundColor: filled ? "#f0fdf4" : "#fef2f2",
    borderLeft: filled ? `5px solid ${COLORS.status.success}` : `5px solid ${COLORS.status.error}`,
  }),
  teamRoleStatusBadge: (filled: boolean) => ({
    backgroundColor: filled ? "#d1fae5" : "#fee2e2",
    color: filled ? "#065f46" : "#991b1b",
    padding: "2px 8px",
    borderRadius: "12px",
    fontSize: "11px",
    fontWeight: "bold" as const,
  }),
  filledDetailsWrapper: {
    marginTop: "10px",
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "8px",
    fontSize: "13px",
    borderTop: "1px solid #e5e7eb",
    paddingTop: "10px",
    color: "#374151",
    marginBottom: "10px",
  },
  filledAssignedName: {
    margin: "0 0 5px 0",
    fontSize: "14px",
    color: "#111827",
  },
  filledReason: {
    margin: "0 0 10px 0",
    fontSize: "14px",
    color: "#4b5563",
    lineHeight: "1.4",
  },
  teamAllocateButton: {
    padding: "5px 10px",
    backgroundColor: COLORS.status.success,
    color: "white",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: "bold" as const,
  },
  riskSummaryContainer: {
    marginTop: "10px",
  },
  riskSummaryBox: {
    padding: "15px",
    borderLeft: `4px solid ${COLORS.status.warning}`,
    backgroundColor: "#fffbeb",
    borderRadius: "4px",
    fontSize: "15px",
    color: "#78350f",
    lineHeight: "1.6",
    fontFamily: "serif",
    fontStyle: "italic",
  },
  riskDisclaimer: {
    fontSize: "12px",
    color: COLORS.text.muted,
    marginTop: "15px",
    borderTop: "1px solid #e5e7eb",
    paddingTop: "10px",
    marginBottom: 0,
  },
};
